[package]
name = "terra-mocks"
version = "0.1.0"
authors = ["Yun Yeo <YunSuk-Yeo@users.noreply.github.com>", "Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Mocks to use for testing Terra Contracts"
repository = "https://github.com/terra-project/cosmwasm-contracts/tree/master/packages/mocks"
license = "Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terra-cosmwasm = { git = "https://github.com/classic-terra/terra-cosmwasm.git", branch = "v3.0.0-proposal", package = "terra-cosmwasm" }
cosmwasm-std = { version = "1.1.0", features = ["stargate","staking"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
